In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
%matplotlib inline

In [28]:
data = pd.read_csv(r"C:\Users\drash\Downloads\milknew.csv")

In [29]:
data

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0     6.6          35      1     0     1          0     254    high
1     6.6          36      0     1     0          1     253    high
2     8.5          70      1     1     1          1     246     low
3     9.5          34      1     1     0          1     255     low
4     6.6          37      0     0     0          0     255  medium
...   ...         ...    ...   ...   ...        ...     ...     ...
1054  6.7          45      1     1     0          0     247  medium
1055  6.7          38      1     0     1          0     255    high
1056  3.0          40      1     1     1          1     255     low
1057  6.8          43      1     0     1          0     250    high
1058  8.6          55      0     1     1          1     255     low

[1059 rows x 8 columns]

In [30]:
data.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [31]:
data.tail()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
1054  6.7          45      1     1     0          0     247  medium
1055  6.7          38      1     0     1          0     255    high
1056  3.0          40      1     1     1          1     255     low
1057  6.8          43      1     0     1          0     250    high
1058  8.6          55      0     1     1          1     255     low

In [32]:
data.describe()

pH   Temprature        Taste         Odor         Fat   \
count  1059.000000  1059.000000  1059.000000  1059.000000  1059.000000   
mean      6.630123    44.226629     0.546742     0.432483     0.671388   
std       1.399679    10.098364     0.498046     0.495655     0.469930   
min       3.000000    34.000000     0.000000     0.000000     0.000000   
25%       6.500000    38.000000     0.000000     0.000000     0.000000   
50%       6.700000    41.000000     1.000000     0.000000     1.000000   
75%       6.800000    45.000000     1.000000     1.000000     1.000000   
max       9.500000    90.000000     1.000000     1.000000     1.000000   

         Turbidity       Colour  
count  1059.000000  1059.000000  
mean      0.491029   251.840415  
std       0.500156     4.307424  
min       0.000000   240.000000  
25%       0.000000   250.000000  
50%       0.000000   255.000000  
75%       1.000000   255.000000  
max       1.000000   255.000000

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


In [34]:
data.isnull().sum()

pH            0
Temprature    0
Taste         0
Odor          0
Fat           0
Turbidity     0
Colour        0
Grade         0
dtype: int64

In [35]:
data.shape

(1059, 8)

In [36]:
data.keys()

Index(['pH', 'Temprature', 'Taste', 'Odor', 'Fat ', 'Turbidity', 'Colour',
       'Grade'],
      dtype='object')

In [37]:
x = data.drop("Grade",axis=1)
x

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour
0     6.6          35      1     0     1          0     254
1     6.6          36      0     1     0          1     253
2     8.5          70      1     1     1          1     246
3     9.5          34      1     1     0          1     255
4     6.6          37      0     0     0          0     255
...   ...         ...    ...   ...   ...        ...     ...
1054  6.7          45      1     1     0          0     247
1055  6.7          38      1     0     1          0     255
1056  3.0          40      1     1     1          1     255
1057  6.8          43      1     0     1          0     250
1058  8.6          55      0     1     1          1     255

[1059 rows x 7 columns]

In [38]:
y = data['Grade']
y

0         high
1         high
2          low
3          low
4       medium
         ...  
1054    medium
1055      high
1056       low
1057      high
1058       low
Name: Grade, Length: 1059, dtype: object

In [39]:
#Data Preprocessing

In [40]:
data['Grade'].unique()

array(['high', 'low', 'medium'], dtype=object)

In [41]:
data['Grade'].value_counts()

low       429
medium    374
high      256
Name: Grade, dtype: int64

In [42]:
#Label Encoder

In [133]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [82]:
label_encoder = preprocessing.LabelEncoder()
data['Grade']= label_encoder.fit_transform(data['Grade'])
data['Grade'].unique()


array([0, 1, 2], dtype=int64)

In [83]:
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [84]:
x = data.drop("Grade",axis=1)
x

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour
0     6.6          35      1     0     1          0     254
1     6.6          36      0     1     0          1     253
2     8.5          70      1     1     1          1     246
3     9.5          34      1     1     0          1     255
4     6.6          37      0     0     0          0     255
...   ...         ...    ...   ...   ...        ...     ...
1054  6.7          45      1     1     0          0     247
1055  6.7          38      1     0     1          0     255
1056  3.0          40      1     1     1          1     255
1057  6.8          43      1     0     1          0     250
1058  8.6          55      0     1     1          1     255

[1059 rows x 7 columns]

In [85]:
y = data['Grade']
y

0       0
1       0
2       1
3       1
4       2
       ..
1054    2
1055    0
1056    1
1057    0
1058    1
Name: Grade, Length: 1059, dtype: int64

In [129]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [87]:
#Confusion Matrix

In [134]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import metrics

In [89]:
#Decision Tree

In [90]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [91]:
pred = model.predict(x_train)
training_data_accuracy = accuracy_score(pred, y_train)
print('Accuracy on Training data : ', training_data_accuracy)


Accuracy on Training data :  1.0


In [92]:
pred = model.predict(x_test)
test_data_accuracy = accuracy_score(pred, y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9905660377358491


In [93]:
metrics.confusion_matrix(pred,y_test)

array([[47,  1,  0],
       [ 0, 77,  0],
       [ 1,  0, 86]], dtype=int64)

In [94]:
accuracy=accuracy_score(y_test,pred)
accuracy

0.9905660377358491

In [95]:
pred

array([0, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2,
       0, 2, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 2, 2, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 0], dtype=int64)

In [96]:
print('Report :')
print(classification_report(y_test, pred)) 

Report :
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        48
           1       1.00      0.99      0.99        78
           2       0.99      1.00      0.99        86

    accuracy                           0.99       212
   macro avg       0.99      0.99      0.99       212
weighted avg       0.99      0.99      0.99       212



In [117]:
#SVM (Support Vector Machine)

In [157]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train) 

SVC()

In [158]:
x_train_pred = classifier.predict(x_train)
training_data_accuracy = accuracy_score(x_train_pred, y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.512396694214876


In [159]:
x_test_prediction = classifier.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.5660377358490566


In [140]:
metrics.confusion_matrix(y_test,x_test_prediction)

array([[ 0, 10, 38],
       [ 0, 41, 37],
       [ 0,  7, 79]], dtype=int64)

In [141]:
accuracy=accuracy_score(y_test,x_test_prediction)
accuracy

0.5660377358490566

In [142]:
x_test_prediction

array([2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2,
       2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1,
       2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2], dtype=int64)

In [143]:
print('Report :')
print(classification_report(y_test, x_test_prediction)) 

Report :
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        48
           1       0.71      0.53      0.60        78
           2       0.51      0.92      0.66        86

    accuracy                           0.57       212
   macro avg       0.41      0.48      0.42       212
weighted avg       0.47      0.57      0.49       212



C:\Users\drash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\drash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\drash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [144]:
#Random Forest Classification

In [145]:
r_model=RandomForestClassifier(n_estimators=100,max_depth=3,random_state=0)
r_model.fit(x_train,y_train)

RandomForestClassifier(max_depth=3, random_state=0)

In [146]:
train_prediction = r_model.predict(x_train)
training_data_accuracy = accuracy_score(train_prediction, y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.922077922077922


In [147]:
test_prediction = r_model.predict(x_test)
test_data_accuracy = accuracy_score(test_prediction, y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9150943396226415


In [148]:
metrics.accuracy_score(test_prediction,y_test)

0.9150943396226415

In [149]:
metrics.confusion_matrix(test_prediction,y_test)

array([[32,  1,  0],
       [ 2, 76,  0],
       [14,  1, 86]], dtype=int64)

In [150]:
print('Report :')
print(classification_report(y_test,test_prediction ))

Report :
              precision    recall  f1-score   support

           0       0.97      0.67      0.79        48
           1       0.97      0.97      0.97        78
           2       0.85      1.00      0.92        86

    accuracy                           0.92       212
   macro avg       0.93      0.88      0.89       212
weighted avg       0.92      0.92      0.91       212



In [151]:
pred

array([0, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2,
       0, 2, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 2, 2, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 0], dtype=int64)